CREATE DATABASE credmo
GO
ALTER DATABASE [credmo] SET COMPATIBILITY_LEVEL = 120
GO
ALTER DATABASE [credmo] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [credmo] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [credmo] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [credmo] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [credmo] SET ARITHABORT OFF 
GO
ALTER DATABASE [credmo] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [credmo] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [credmo] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [credmo] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [credmo] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [credmo] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [credmo] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [credmo] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [credmo] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [credmo] SET  DISABLE_BROKER 
GO
ALTER DATABASE [credmo] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [credmo] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [credmo] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [credmo] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [credmo] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [credmo] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [credmo] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [credmo] SET RECOVERY FULL 
GO
ALTER DATABASE [credmo] SET  MULTI_USER 
GO
ALTER DATABASE [credmo] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [credmo] SET DB_CHAINING OFF 
GO
ALTER DATABASE [credmo] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [credmo] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [credmo] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [credmo] SET  READ_WRITE 
GO
USE [credmo]
GO
